# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Kaggle Courses
site_url: https://github.com/fralfaro/kaggle-courses
site_author: Francisco Alfaro
site_description:

# Repository
repo_name: fralfaro/kaggle-courses
repo_url: https://github.com/fralfaro/kaggle-courses
edit_uri: ''


# Markdown extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: en
  logo: images/logo.bmp
  favicon: images/logo_python.svg
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/kaggle
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kaggle
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/kaggle/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/kaggle


# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search

# TOC
nav:
    - index.md
    - Intro to Programming:
        - kaggle/01. Intro to Programming/tutorial/01. arithmetic-and-variables.ipynb
        - kaggle/01. Intro to Programming/tutorial/02. functions.ipynb
        - kaggle/01. Intro to Programming/tutorial/03. data-types.ipynb
        - kaggle/01. Intro to Programming/tutorial/04. conditions-and-conditional-statements.ipynb
        - kaggle/01. Intro to Programming/tutorial/05. intro-to-lists.ipynb
    - Python:
        - kaggle/02. Python/tutorial/01. hello-python.ipynb
        - kaggle/02. Python/tutorial/02. functions-and-getting-help.ipynb
        - kaggle/02. Python/tutorial/03. booleans-and-conditionals.ipynb
        - kaggle/02. Python/tutorial/04. lists.ipynb
        - kaggle/02. Python/tutorial/05. loops-and-list-comprehensions.ipynb
        - kaggle/02. Python/tutorial/06. strings-and-dictionaries.ipynb
        - Working with External Libraries: kaggle/02. Python/tutorial/07. working-with-external-libraries

    - Intro to Machine Learning:
        - kaggle/03. Intro to Machine Learning/tutorial/01. how-models-work.ipynb
        - kaggle/03. Intro to Machine Learning/tutorial/02. basic-data-exploration.ipynb
        - kaggle/03. Intro to Machine Learning/tutorial/03. your-first-machine-learning-model.ipynb
        - kaggle/03. Intro to Machine Learning/tutorial/04. model-validation.ipynb
        - kaggle/03. Intro to Machine Learning/tutorial/05. underfitting-and-overfitting.ipynb
        - kaggle/03. Intro to Machine Learning/tutorial/06. random-forests.ipynb
        - kaggle/03. Intro to Machine Learning/tutorial/07. machine-learning-competitions.ipynb






